# Generated by Django 3.0.2 on 2020-02-02 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenstrack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[expenstrack.models.validateTitle, expenstrack.models.greaterThanFive])),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='income/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[expenstrack.models.validateTitle, expenstrack.models.greaterThanFive])),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
